In [1]:
import pandas as pd
import os
import datetime
import requests
from datetime import datetime

In [ ]:
result = pd.read_csv('result_allQs_D.csv')

In [3]:
result['hourlocal'] = result.datetimelocal.str[11:13]

In [4]:
result['hour_local'] = result.hourlocal.str[0:2].astype(float)

In [5]:
result.rename(columns = {'Start station number':'Start_station_number'}, inplace = True)

In [ ]:
#result4['Start_Station_Number'] = result4.Start_station_number.astype(str)

In [8]:
result.shape

(27422425, 21)

In [11]:
result = result[result.Start_station_number == 31258]

In [12]:
result

,atemperatue,humidity,temperature,datetime_x,windSpeed,datetimelocal,Start date,Duration,End date,Start_station_number,...,End station number,End station,Bike number,Member type,latstart,lonstart,latend,lonend,hourlocal,hour_local
598,9.46,0.92,9.46,2017-01-21 15:00:00-05:00,2.83,2017-01-21 15:00:00,2017-01-21 15:31:47,0 days 00:34:44.000000000,2017-01-21 16:06:32,31258,...,31208,M St & New Jersey Ave SE,W21070,Member,38.888251,-77.049426,38.876300,-77.003700,15,15.0
599,9.46,0.92,9.46,2017-01-21 15:00:00-05:00,2.83,2017-01-21 15:00:00,2017-01-21 15:31:48,0 days 00:34:44.000000000,2017-01-21 16:06:33,31258,...,31208,M St & New Jersey Ave SE,W21247,Member,38.888251,-77.049426,38.876300,-77.003700,15,15.0
600,9.46,0.92,9.46,2017-01-21 15:00:00-05:00,2.83,2017-01-21 15:00:00,2017-01-21 15:31:47,0 days 00:34:44.000000000,2017-01-21 16:06:32,31258,...,31208,M St & New Jersey Ave SE,W21070,Member,38.888251,-77.049426,38.876300,-77.003700,15,15.0
601,9.46,0.92,9.46,2017-01-21 15:00:00-05:00,2.83,2017-01-21 15:00:00,2017-01-21 15:31:48,0 days 00:34:44.000000000,2017-01-21 16:06:33,31258,...,31208,M St & New Jersey Ave SE,W21247,Member,38.888251,-77.049426,38.876300,-77.003700,15,15.0
602,9.46,0.92,9.46,2017-01-21 15:00:00-05:00,2.83,2017-01-21 15:00:00,2017-01-21 15:31:47,0 days 00:34:44.000000000,2017-01-21 16:06:32,31258,...,31208,M St & New Jersey Ave SE,W21070,Member,38.888251,-77.049426,38.876300,-77.003700,15,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27219189,20.51,0.76,20.43,2017-11-06 17:00:00-05:00,0.21,2017-11-06 17:00:00,2017-11-06 17:38:00,0 days 00:24:23.000000000,2017-11-06 18:02:24,31258,...,31070,Arlington Blvd & Fillmore St,W20936,Member,38.888251,-77.049426,38.873755,-77.089233,17,17.0
27219190,20.51,0.76,20.43,2017-11-06 17:00:00-05:00,0.21,2017-11-06 17:00:00,2017-11-06 17:37:40,0 days 00:24:46.000000000,2017-11-06 18:02:27,31258,...,31070,Arlington Blvd & Fillmore St,W20634,Member,38.888251,-77.049426,38.873755,-77.089233,17,17.0
27219191,20.51,0.76,20.43,2017-11-06 17:00:00-05:00,0.21,2017-11-06 17:00:00,2017-11-06 17:38:00,0 days 00:24:23.000000000,2017-11-06 18:02:24,31258,...,31070,Arlington Blvd & Fillmore St,W20936,Member,38.888251,-77.049426,38.873755,-77.089233,17,17.0
27219192,20.51,0.76,20.43,2017-11-06 17:00:00-05:00,0.21,2017-11-06 17:00:00,2017-11-06 17:37:40,0 days 00:24:46.000000000,2017-11-06 18:02:27,31258,...,31070,Arlington Blvd & Fillmore St,W20634,Member,38.888251,-77.049426,38.873755,-77.089233,17,17.0
27219193,20.51,0.76,20.43,2017-11-06 17:00:00-05:00,0.21,2017-11-06 17:00:00,2017-11-06 17:38:00,0 days 00:24:23.000000000,2017-11-06 18:02:24,31258,...,31070,Arlington Blvd & Fillmore St,W20936,Member,38.888251,-77.049426,38.873755,-77.089233,17,17.0

In [14]:
result.to_csv('resultStartStation31258.csv', index=False)