In [1]:
import pandas as pd
import os
import datetime
import requests
from datetime import datetime

In [2]:
result = pd.read_csv('result_allQs_D.csv')

In [3]:
result['hourlocal'] = result.datetimelocal.str[11:13]

In [4]:
result['hour_local'] = result.hourlocal.str[0:2].astype(float)

In [5]:
result.rename(columns = {'Start station number':'Start_station_number'}, inplace = True)

In [6]:
#result4['Start_Station_Number'] = result4.Start_station_number.astype(str)

In [7]:
result.shape

(27422425, 21)

In [8]:
result = result[result.Start_station_number == 31623]

In [9]:
result

,atemperatue,humidity,temperature,datetime_x,windSpeed,datetimelocal,Start date,Duration,End date,Start_station_number,...,End station number,End station,Bike number,Member type,latstart,lonstart,latend,lonend,hourlocal,hour_local
2340,5.78,0.92,5.78,2017-01-03 08:00:00-05:00,3.69,2017-01-03 08:00:00,2017-01-03 08:07:14,0 days 00:12:30.000000000,2017-01-03 08:19:45,31623,...,31208,M St & New Jersey Ave SE,W20556,Member,38.89696,-77.00493,38.876300,-77.003700,08,8.0
2341,5.78,0.92,5.78,2017-01-03 08:00:00-05:00,3.69,2017-01-03 08:00:00,2017-01-03 08:43:24,0 days 00:12:24.000000000,2017-01-03 08:55:49,31623,...,31208,M St & New Jersey Ave SE,W00225,Member,38.89696,-77.00493,38.876300,-77.003700,08,8.0
2342,5.78,0.92,5.78,2017-01-03 08:00:00-05:00,3.69,2017-01-03 08:00:00,2017-01-03 08:07:14,0 days 00:12:30.000000000,2017-01-03 08:19:45,31623,...,31208,M St & New Jersey Ave SE,W20556,Member,38.89696,-77.00493,38.876300,-77.003700,08,8.0
2343,5.78,0.92,5.78,2017-01-03 08:00:00-05:00,3.69,2017-01-03 08:00:00,2017-01-03 08:43:24,0 days 00:12:24.000000000,2017-01-03 08:55:49,31623,...,31208,M St & New Jersey Ave SE,W00225,Member,38.89696,-77.00493,38.876300,-77.003700,08,8.0
2344,5.78,0.92,5.78,2017-01-03 08:00:00-05:00,3.69,2017-01-03 08:00:00,2017-01-03 08:07:14,0 days 00:12:30.000000000,2017-01-03 08:19:45,31623,...,31208,M St & New Jersey Ave SE,W20556,Member,38.89696,-77.00493,38.876300,-77.003700,08,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27368354,21.77,0.43,21.77,2017-10-20 18:00:00-04:00,2.90,2017-10-20 18:00:00,2017-10-20 18:22:49,0 days 00:41:39.000000000,2017-10-20 19:04:28,31623,...,31713,Division Ave & Foote St NE,W20417,Casual,38.89696,-77.00493,38.897407,-76.925907,18,18.0
27368355,21.77,0.43,21.77,2017-10-20 18:00:00-04:00,2.90,2017-10-20 18:00:00,2017-10-20 18:22:51,0 days 00:41:30.000000000,2017-10-20 19:04:22,31623,...,31713,Division Ave & Foote St NE,W20920,Member,38.89696,-77.00493,38.897407,-76.925907,18,18.0
27368356,21.77,0.43,21.77,2017-10-20 18:00:00-04:00,2.90,2017-10-20 18:00:00,2017-10-20 18:22:46,0 days 00:41:38.000000000,2017-10-20 19:04:25,31623,...,31713,Division Ave & Foote St NE,W22375,Casual,38.89696,-77.00493,38.897407,-76.925907,18,18.0
27368357,21.77,0.43,21.77,2017-10-20 18:00:00-04:00,2.90,2017-10-20 18:00:00,2017-10-20 18:22:49,0 days 00:41:39.000000000,2017-10-20 19:04:28,31623,...,31713,Division Ave & Foote St NE,W20417,Casual,38.89696,-77.00493,38.897407,-76.925907,18,18.0
27368358,21.77,0.43,21.77,2017-10-20 18:00:00-04:00,2.90,2017-10-20 18:00:00,2017-10-20 18:22:51,0 days 00:41:30.000000000,2017-10-20 19:04:22,31623,...,31713,Division Ave & Foote St NE,W20920,Member,38.89696,-77.00493,38.897407,-76.925907,18,18.0

In [10]:
result.to_csv('resultStartStation31623.csv', index=False)